version: '3.8'

services:
  app:
    image: node:19-alpine
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Password123!
      MYSQL_DB: mariadb_is_awesome
    depends_on:
      - mdb
    networks:
      - my-network

  mdb:
    image: mariadb:latest
    container_name: mdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Password123!"
      MYSQL_DATABASE: "mariadb_is_awesome"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
